### ISSUE TITLE
Loaction reset. Starts again.

### ISSUE THREAD

**Issue by IGDanie** [GediminasMasaitis/PokeEase#8] opened 2016-08-11 22:47 UTC
Occasionally jumps randomly and starts in a new location for a unknown reason. https://gyazo.com/0411e2d4fdfe93b7af0425cfcd43bcee 

The break in the image is two separate lines.

**Comment by GediminasMasaitis** [comment] 2016-08-12 12:11
Duplicate of #9

**Closed as completed by GediminasMasaitis** 2016-08-12 12:11 UTC
Labels: bug, duplicate
